use musicorganizer;
CREATE TABLE genres(
   GenreID                                 INTEGER  NOT NULL PRIMARY KEY 
  ,GenreName                               VARCHAR(26) NOT NULL
  ,DescriptionLink                         VARCHAR(54) NOT NULL
);
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (2,'Acid rock','https://en.wikipedia.org/wiki/acidrock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (3,'African blues','https://en.wikipedia.org/wiki/africanblues');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (4,'Afro punk','https://en.wikipedia.org/wiki/afropunk');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (5,'Alternative country','https://en.wikipedia.org/wiki/alternativecountry');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (6,'Alternative dance','https://en.wikipedia.org/wiki/alternativedance');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (7,'Alternative metal','https://en.wikipedia.org/wiki/alternativemetal');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (8,'Alternative rock','https://en.wikipedia.org/wiki/alternativerock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (9,'Anatolian rock','https://en.wikipedia.org/wiki/anatolianrock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (10,'Art punk','https://en.wikipedia.org/wiki/artpunk');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (11,'Art rock','https://en.wikipedia.org/wiki/artrock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (12,'Baggy','https://en.wikipedia.org/wiki/baggy');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (13,'Bandana Thrash','https://en.wikipedia.org/wiki/bandanathrash');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (14,'Baroque pop','https://en.wikipedia.org/wiki/baroquepop');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (15,'Beach music','https://en.wikipedia.org/wiki/beachmusic');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (16,'Beat','https://en.wikipedia.org/wiki/beat');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (17,'Bent edge','https://en.wikipedia.org/wiki/bentedge');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (18,'Big beat','https://en.wikipedia.org/wiki/bigbeat');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (19,'Bisrock','https://en.wikipedia.org/wiki/bisrock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (20,'Black metal','https://en.wikipedia.org/wiki/blackmetal');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (21,'Blues rock','https://en.wikipedia.org/wiki/bluesrock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (22,'Blues-rock','https://en.wikipedia.org/wiki/blues-rock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (23,'Boogie rock','https://en.wikipedia.org/wiki/boogierock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (24,'Boogie-woogie','https://en.wikipedia.org/wiki/boogie-woogie');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (25,'Brazilian thrash metal','https://en.wikipedia.org/wiki/brazilianthrashmetal');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (26,'Breakcore','https://en.wikipedia.org/wiki/breakcore');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (27,'British blues','https://en.wikipedia.org/wiki/britishblues');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (28,'Britpop','https://en.wikipedia.org/wiki/britpop');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (29,'Canadian blues','https://en.wikipedia.org/wiki/canadianblues');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (30,'Canterbury sound','https://en.wikipedia.org/wiki/canterburysound');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (31,'Cello rock','https://en.wikipedia.org/wiki/cellorock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (32,'Celtic metal','https://en.wikipedia.org/wiki/celticmetal');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (33,'Celtic punk','https://en.wikipedia.org/wiki/celticpunk');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (34,'Celtic rock','https://en.wikipedia.org/wiki/celticrock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (35,'Chicago blues','https://en.wikipedia.org/wiki/chicagoblues');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (36,'Chicano rock','https://en.wikipedia.org/wiki/chicanorock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (37,'Christian alternative rock','https://en.wikipedia.org/wiki/christianalternativerock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (38,'Christian metal','https://en.wikipedia.org/wiki/christianmetal');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (39,'Christian punk','https://en.wikipedia.org/wiki/christianpunk');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (40,'Christian rock','https://en.wikipedia.org/wiki/christianrock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (41,'Classic female blues','https://en.wikipedia.org/wiki/classicfemaleblues');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (42,'Cock rock','https://en.wikipedia.org/wiki/cockrock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (43,'Coldwave','https://en.wikipedia.org/wiki/coldwave');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (44,'College rock','https://en.wikipedia.org/wiki/collegerock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (45,'Comedy rock','https://en.wikipedia.org/wiki/comedyrock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (46,'Contemporary R&B','https://en.wikipedia.org/wiki/contemporaryr&b');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (47,'Country blues','https://en.wikipedia.org/wiki/countryblues');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (48,'Country rock','https://en.wikipedia.org/wiki/countryrock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (49,'Cowpunk','https://en.wikipedia.org/wiki/cowpunk');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (50,'Crossover thrash','https://en.wikipedia.org/wiki/crossoverthrash');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (51,'Crunkcore','https://en.wikipedia.org/wiki/crunkcore');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (52,'Crust punk','https://en.wikipedia.org/wiki/crustpunk');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (53,'D-beat','https://en.wikipedia.org/wiki/d-beat');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (54,'Dance-punk','https://en.wikipedia.org/wiki/dance-punk');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (55,'Dance-rock','https://en.wikipedia.org/wiki/dance-rock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (56,'Dark cabaret','https://en.wikipedia.org/wiki/darkcabaret');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (57,'Dark rock','https://en.wikipedia.org/wiki/darkrock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (58,'Darkwave','https://en.wikipedia.org/wiki/darkwave');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (59,'Death ''n'' roll','https://en.wikipedia.org/wiki/death''n''roll');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (60,'Death metal','https://en.wikipedia.org/wiki/deathmetal');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (61,'Death rock','https://en.wikipedia.org/wiki/deathrock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (62,'Death/doom','https://en.wikipedia.org/wiki/death/doom');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (63,'Deathcore','https://en.wikipedia.org/wiki/deathcore');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (64,'Deathgrind','https://en.wikipedia.org/wiki/deathgrind');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (65,'Delta blues','https://en.wikipedia.org/wiki/deltablues');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (66,'Detroit blues','https://en.wikipedia.org/wiki/detroitblues');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (67,'Digital hardcore','https://en.wikipedia.org/wiki/digitalhardcore');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (68,'Dirty blues','https://en.wikipedia.org/wiki/dirtyblues');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (69,'Djent','https://en.wikipedia.org/wiki/djent');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (70,'Doom metal','https://en.wikipedia.org/wiki/doommetal');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (71,'Dream pop','https://en.wikipedia.org/wiki/dreampop');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (72,'Drone metal','https://en.wikipedia.org/wiki/dronemetal');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (73,'Dunedin sound','https://en.wikipedia.org/wiki/dunedinsound');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (74,'Electric blues','https://en.wikipedia.org/wiki/electricblues');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (75,'Electric folk','https://en.wikipedia.org/wiki/electricfolk');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (76,'Electroclash','https://en.wikipedia.org/wiki/electroclash');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (77,'Electronic rock','https://en.wikipedia.org/wiki/electronicrock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (78,'Electronicore','https://en.wikipedia.org/wiki/electronicore');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (79,'Electropunk','https://en.wikipedia.org/wiki/electropunk');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (80,'Emo','https://en.wikipedia.org/wiki/emo');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (81,'Ethereal wave','https://en.wikipedia.org/wiki/etherealwave');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (82,'Experimental metal','https://en.wikipedia.org/wiki/experimentalmetal');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (83,'Experimental rock','https://en.wikipedia.org/wiki/experimentalrock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (84,'Extreme metal','https://en.wikipedia.org/wiki/extrememetal');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (85,'Flamenco rock','https://en.wikipedia.org/wiki/flamencorock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (86,'Folk metal','https://en.wikipedia.org/wiki/folkmetal');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (87,'Folk punk','https://en.wikipedia.org/wiki/folkpunk');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (88,'Folk rock','https://en.wikipedia.org/wiki/folkrock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (89,'Funk metal','https://en.wikipedia.org/wiki/funkmetal');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (90,'Funk rock','https://en.wikipedia.org/wiki/funkrock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (91,'Garage punk','https://en.wikipedia.org/wiki/garagepunk');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (92,'Garage rock','https://en.wikipedia.org/wiki/garagerock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (93,'Geek rock','https://en.wikipedia.org/wiki/geekrock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (94,'Glam metal','https://en.wikipedia.org/wiki/glammetal');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (95,'Glam punk','https://en.wikipedia.org/wiki/glampunk');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (96,'Glam rock','https://en.wikipedia.org/wiki/glamrock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (97,'Goregrind','https://en.wikipedia.org/wiki/goregrind');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (98,'Gospel blues','https://en.wikipedia.org/wiki/gospelblues');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (99,'Gothabilly','https://en.wikipedia.org/wiki/gothabilly');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (100,'Gothic metal','https://en.wikipedia.org/wiki/gothicmetal');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (101,'Gothic rock','https://en.wikipedia.org/wiki/gothicrock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (102,'Grebo','https://en.wikipedia.org/wiki/grebo');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (103,'Grindcore','https://en.wikipedia.org/wiki/grindcore');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (104,'Grindie','https://en.wikipedia.org/wiki/grindie');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (105,'Groove metal','https://en.wikipedia.org/wiki/groovemetal');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (106,'Group Sounds','https://en.wikipedia.org/wiki/groupsounds');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (107,'Grunge','https://en.wikipedia.org/wiki/grunge');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (108,'Gypsy punk','https://en.wikipedia.org/wiki/gypsypunk');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (109,'Hard rock','https://en.wikipedia.org/wiki/hardrock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (110,'Hardcore punk','https://en.wikipedia.org/wiki/hardcorepunk');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (111,'Heartland rock','https://en.wikipedia.org/wiki/heartlandrock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (112,'Heavy metal','https://en.wikipedia.org/wiki/heavymetal');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (113,'Hill country blues','https://en.wikipedia.org/wiki/hillcountryblues');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (114,'Hip hop','https://en.wikipedia.org/wiki/hiphop');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (115,'Hokum blues','https://en.wikipedia.org/wiki/hokumblues');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (116,'Horror punk','https://en.wikipedia.org/wiki/horrorpunk');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (117,'Indie folk','https://en.wikipedia.org/wiki/indiefolk');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (118,'Indie pop','https://en.wikipedia.org/wiki/indiepop');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (119,'Indie rock','https://en.wikipedia.org/wiki/indierock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (120,'Indietronica','https://en.wikipedia.org/wiki/indietronica');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (121,'Indorock','https://en.wikipedia.org/wiki/indorock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (122,'Industrial metal','https://en.wikipedia.org/wiki/industrialmetal');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (123,'Industrial rock','https://en.wikipedia.org/wiki/industrialrock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (124,'Instrumental rock','https://en.wikipedia.org/wiki/instrumentalrock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (125,'Italian occult psychedelia','https://en.wikipedia.org/wiki/italianoccultpsychedelia');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (126,'Jangle pop','https://en.wikipedia.org/wiki/janglepop');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (127,'Jazz blues','https://en.wikipedia.org/wiki/jazzblues');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (128,'Jazz rock','https://en.wikipedia.org/wiki/jazzrock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (129,'Jersey Shore sound','https://en.wikipedia.org/wiki/jerseyshoresound');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (130,'Jump blues','https://en.wikipedia.org/wiki/jumpblues');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (131,'Kansas City blues','https://en.wikipedia.org/wiki/kansascityblues');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (132,'Kawaii metal','https://en.wikipedia.org/wiki/kawaiimetal');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (133,'Krautrock','https://en.wikipedia.org/wiki/krautrock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (134,'Latin alternative','https://en.wikipedia.org/wiki/latinalternative');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (135,'Latin metal','https://en.wikipedia.org/wiki/latinmetal');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (136,'Latin rock','https://en.wikipedia.org/wiki/latinrock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (137,'Louisiana blues','https://en.wikipedia.org/wiki/louisianablues');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (138,'Madchester','https://en.wikipedia.org/wiki/madchester');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (139,'Manila Sound','https://en.wikipedia.org/wiki/manilasound');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (140,'Math rock','https://en.wikipedia.org/wiki/mathrock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (141,'Mathcore','https://en.wikipedia.org/wiki/mathcore');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (142,'Medieval folk rock','https://en.wikipedia.org/wiki/medievalfolkrock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (143,'Medieval metal','https://en.wikipedia.org/wiki/medievalmetal');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (144,'Melodic death metal','https://en.wikipedia.org/wiki/melodicdeathmetal');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (145,'Melodic hardcore','https://en.wikipedia.org/wiki/melodichardcore');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (146,'Memphis blues','https://en.wikipedia.org/wiki/memphisblues');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (147,'Metalcore','https://en.wikipedia.org/wiki/metalcore');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (148,'Mod revival','https://en.wikipedia.org/wiki/modrevival');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (149,'Nardcore','https://en.wikipedia.org/wiki/nardcore');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (150,'Neo-classical metal','https://en.wikipedia.org/wiki/neo-classicalmetal');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (151,'Neo-prog','https://en.wikipedia.org/wiki/neo-prog');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (152,'Neo-psychedelia','https://en.wikipedia.org/wiki/neo-psychedelia');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (153,'Neoclassical dark wave','https://en.wikipedia.org/wiki/neoclassicaldarkwave');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (154,'Neue Deutsche Härte','https://en.wikipedia.org/wiki/neuedeutschehärte');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (155,'Neue Deutsche Welle','https://en.wikipedia.org/wiki/neuedeutschewelle');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (156,'New Orleans blues','https://en.wikipedia.org/wiki/neworleansblues');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (157,'New rave','https://en.wikipedia.org/wiki/newrave');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (158,'New wave','https://en.wikipedia.org/wiki/newwave');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (159,'New wave of new wave','https://en.wikipedia.org/wiki/newwaveofnewwave');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (160,'New Weird America','https://en.wikipedia.org/wiki/newweirdamerica');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (161,'Nintendocore','https://en.wikipedia.org/wiki/nintendocore');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (162,'Noise pop','https://en.wikipedia.org/wiki/noisepop');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (163,'Noise rock','https://en.wikipedia.org/wiki/noiserock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (164,'Nu gaze','https://en.wikipedia.org/wiki/nugaze');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (165,'Nu metal','https://en.wikipedia.org/wiki/numetal');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (166,'Ostrock','https://en.wikipedia.org/wiki/ostrock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (167,'Pagan metal','https://en.wikipedia.org/wiki/paganmetal');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (168,'Pagan rock','https://en.wikipedia.org/wiki/paganrock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (169,'Paisley Underground','https://en.wikipedia.org/wiki/paisleyunderground');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (170,'Piano blues','https://en.wikipedia.org/wiki/pianoblues');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (171,'Piedmont blues','https://en.wikipedia.org/wiki/piedmontblues');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (172,'Pinoy rock','https://en.wikipedia.org/wiki/pinoyrock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (173,'Pirate metal','https://en.wikipedia.org/wiki/piratemetal');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (174,'Pop punk','https://en.wikipedia.org/wiki/poppunk');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (175,'Pop rock','https://en.wikipedia.org/wiki/poprock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (176,'Pornogrind','https://en.wikipedia.org/wiki/pornogrind');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (177,'Post-Britpop','https://en.wikipedia.org/wiki/post-britpop');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (178,'Post-grunge','https://en.wikipedia.org/wiki/post-grunge');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (179,'Post-hardcore','https://en.wikipedia.org/wiki/post-hardcore');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (180,'Post-metal','https://en.wikipedia.org/wiki/post-metal');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (181,'Post-punk','https://en.wikipedia.org/wiki/post-punk');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (182,'Post-punk revival','https://en.wikipedia.org/wiki/post-punkrevival');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (183,'Post-rock','https://en.wikipedia.org/wiki/post-rock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (184,'Power metal','https://en.wikipedia.org/wiki/powermetal');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (185,'Power pop','https://en.wikipedia.org/wiki/powerpop');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (186,'Powerviolence','https://en.wikipedia.org/wiki/powerviolence');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (187,'Progressive metal','https://en.wikipedia.org/wiki/progressivemetal');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (188,'Progressive rock','https://en.wikipedia.org/wiki/progressiverock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (189,'Protopunk','https://en.wikipedia.org/wiki/protopunk');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (190,'Psychedelic rock','https://en.wikipedia.org/wiki/psychedelicrock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (191,'Psychobilly','https://en.wikipedia.org/wiki/psychobilly');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (192,'Pub rock (Australia)','https://en.wikipedia.org/wiki/pubrock(australia)');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (193,'Pub rock (United Kingdom)','https://en.wikipedia.org/wiki/pubrock(unitedkingdom)');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (194,'Punk blues','https://en.wikipedia.org/wiki/punkblues');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (195,'Punk blues','https://en.wikipedia.org/wiki/punkblues');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (196,'Punk jazz','https://en.wikipedia.org/wiki/punkjazz');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (197,'Punk rock','https://en.wikipedia.org/wiki/punkrock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (198,'Queercore','https://en.wikipedia.org/wiki/queercore');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (199,'Raga rock','https://en.wikipedia.org/wiki/ragarock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (200,'Rap metal','https://en.wikipedia.org/wiki/rapmetal');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (201,'Rap rock','https://en.wikipedia.org/wiki/raprock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (202,'Rapcore','https://en.wikipedia.org/wiki/rapcore');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (203,'Reggae rock','https://en.wikipedia.org/wiki/reggaerock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (204,'Rhythm and blues (R&B)','https://en.wikipedia.org/wiki/rhythmandblues(r&b)');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (205,'Riot grrrl','https://en.wikipedia.org/wiki/riotgrrrl');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (206,'Rock Against Communism','https://en.wikipedia.org/wiki/rockagainstcommunism');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (207,'Rock and roll','https://en.wikipedia.org/wiki/rockandroll');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (208,'Rock in Opposition','https://en.wikipedia.org/wiki/rockinopposition');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (209,'Rockabilly','https://en.wikipedia.org/wiki/rockabilly');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (210,'Roots rock','https://en.wikipedia.org/wiki/rootsrock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (211,'Sadcore','https://en.wikipedia.org/wiki/sadcore');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (212,'Samba rock','https://en.wikipedia.org/wiki/sambarock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (213,'Screamo','https://en.wikipedia.org/wiki/screamo');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (214,'Shock rock','https://en.wikipedia.org/wiki/shockrock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (215,'Shoegazing','https://en.wikipedia.org/wiki/shoegazing');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (216,'Ska punk','https://en.wikipedia.org/wiki/skapunk');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (217,'Skate punk','https://en.wikipedia.org/wiki/skatepunk');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (218,'Slowcore','https://en.wikipedia.org/wiki/slowcore');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (219,'Sludge metal','https://en.wikipedia.org/wiki/sludgemetal');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (220,'Soft rock','https://en.wikipedia.org/wiki/softrock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (221,'Soul blues','https://en.wikipedia.org/wiki/soulblues');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (222,'Southern metal','https://en.wikipedia.org/wiki/southernmetal');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (223,'Southern rock','https://en.wikipedia.org/wiki/southernrock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (224,'Space rock','https://en.wikipedia.org/wiki/spacerock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (225,'Speed metal','https://en.wikipedia.org/wiki/speedmetal');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (226,'St. Louis blues','https://en.wikipedia.org/wiki/st.louisblues');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (227,'Stoner rock','https://en.wikipedia.org/wiki/stonerrock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (228,'Straight edge','https://en.wikipedia.org/wiki/straightedge');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (229,'Street punk','https://en.wikipedia.org/wiki/streetpunk');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (230,'Sufi rock','https://en.wikipedia.org/wiki/sufirock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (231,'Sunshine pop','https://en.wikipedia.org/wiki/sunshinepop');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (232,'Surf music','https://en.wikipedia.org/wiki/surfmusic');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (233,'Swamp blues','https://en.wikipedia.org/wiki/swampblues');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (234,'Swamp pop','https://en.wikipedia.org/wiki/swamppop');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (235,'Swedish death metal','https://en.wikipedia.org/wiki/swedishdeathmetal');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (236,'Symphonic black metal','https://en.wikipedia.org/wiki/symphonicblackmetal');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (237,'Symphonic metal','https://en.wikipedia.org/wiki/symphonicmetal');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (238,'Symphonic rock','https://en.wikipedia.org/wiki/symphonicrock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (239,'Synthpop','https://en.wikipedia.org/wiki/synthpop');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (240,'Taqwacore','https://en.wikipedia.org/wiki/taqwacore');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (241,'Technical death metal','https://en.wikipedia.org/wiki/technicaldeathmetal');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (242,'Teutonic thrash metal','https://en.wikipedia.org/wiki/teutonicthrashmetal');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (243,'Texas blues','https://en.wikipedia.org/wiki/texasblues');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (244,'Thrash metal','https://en.wikipedia.org/wiki/thrashmetal');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (245,'Thrashcore','https://en.wikipedia.org/wiki/thrashcore');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (246,'Traditional heavy metal','https://en.wikipedia.org/wiki/traditionalheavymetal');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (247,'Trop rock','https://en.wikipedia.org/wiki/troprock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (248,'Tulsa Sound','https://en.wikipedia.org/wiki/tulsasound');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (249,'Unblack metal','https://en.wikipedia.org/wiki/unblackmetal');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (250,'Viking metal','https://en.wikipedia.org/wiki/vikingmetal');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (251,'Viking rock','https://en.wikipedia.org/wiki/vikingrock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (252,'Visual kei','https://en.wikipedia.org/wiki/visualkei');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (253,'Wagnerian rock','https://en.wikipedia.org/wiki/wagnerianrock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (254,'War metal','https://en.wikipedia.org/wiki/warmetal');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (255,'West Coast blues','https://en.wikipedia.org/wiki/westcoastblues');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (256,'Wizard rock','https://en.wikipedia.org/wiki/wizardrock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (257,'Yacht rock','https://en.wikipedia.org/wiki/yachtrock');
INSERT INTO genres(GenreID,GenreName,DescriptionLink) VALUES (258,'Youth crew','https://en.wikipedia.org/wiki/youthcrew');
